require 'nokogiri'
require 'open-uri'
require 'pry'
require 'colorize'
require 'colorized_string'
require_relative "./resort_report/version"
require_relative "./resort_report/report"
require_relative './resort_report/cli'
require_relative "./resort_report/scraper"
